Repository goorm-CHACHA/FE, pull requests merged in 2025-03, with the labels that each got.

#14 feat: 카드 컴포넌트 제작
  app/page.tsx
  src/components/common/alert.tsx
  src/components/common/button.tsx
  src/components/common/card.tsx
  src/components/common/chat-bubble.tsx
Labels: Feature

#21 feat: 공통컴포넌트 말풍선 모양 변경
  src/components/common/chat-bubble.tsx
Labels: Feature

#19 Feat: 공통 컴포넌트 모달창 제작
  package-lock.json
  package.json
  src/components/common/modalOneBtn.tsx
  src/components/common/modalTwoBtn.tsx
Labels: Feature

#22 feat: Input 컴포넌트 제작
  app/account/find-id/page.tsx
  app/account/find-pw/page.tsx
  app/account/login/page.tsx
  app/account/register/page.tsx
  package-lock.json
  package.json
  src/components/common/input.tsx
  src/schema/user.ts
Labels: Feature

#18 feat: 공통 컴포넌트 프로필 제작
  app/page.tsx
  src/components/common/default-profile.tsx
  src/components/common/profile.tsx
Labels: Feature

#23 feat : 공통컴포넌트 네비게이션 제작
  app/page.tsx
  package-lock.json
  src/components/common/bottom-nav.tsx
  src/components/common/modalOneBtn.tsx
  src/components/common/modalTwoBtn.tsx
Labels: Feature

#27 chore: radix ui 설치
  package-lock.json
  package.json
  src/components/common/modal-one-btn.tsx
  src/components/common/modal-two-btn.tsx
  tailwind.config.ts
Labels: chore

#29 feat: 공통 컴포넌트 multiple selection 제작
  app/page.tsx
  src/components/common/multiple-selection.tsx
Labels: Feature

#30 feat: 페이지 레이아웃 설계 - 로그인, 아이디 비밀번호 찾기
  app/(bottom-layout)/layout.tsx
  app/(main-layout)/home/page.tsx
  app/(main-layout)/layout.tsx
  app/(plain)/account/find-id-pw/page.tsx
  app/(plain)/account/login/page.tsx
  app/(plain)/account/register/page.tsx
  app/(plain)/landing/page.tsx
  app/(top-layout)/layout.tsx
  app/account/find-pw/page.tsx
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
  src/components/account/find-id-form.tsx
  src/components/account/find-password-form.tsx
  src/components/common/bottom-nav.tsx
  src/components/common/chips.tsx
  src/components/common/default-profile.tsx
  src/components/common/input.tsx
  src/components/common/multiple-selection.tsx
  src/components/common/profile.tsx
  src/components/common/radix-tabs.tsx
  src/schema/user.ts
Labels: Feature

#32 feat : 페이지 레이아웃 설계 - 매칭
  app/(main-layout)/home/page.tsx
  app/(top-layout)/chat/page.tsx
  app/page.tsx
  package-lock.json
  package.json
  src/components/common/profile.tsx
  src/components/common/radix-tabs.tsx
  src/components/common/switch.tsx
  src/components/common/top-nav.tsx
  src/components/match/group.tsx
  src/components/match/one-to-one.tsx
Labels: Feature

#37 feat: 페이지 레이아웃 채팅 설계
  app/(top-layout)/chat/page.tsx
  app/page.tsx
  src/components/chat/chat-bubble.tsx
  src/components/chat/chat-window.tsx
  src/components/chat/message-input.tsx
  src/components/common/top-nav.tsx
Labels: Feature

#38 feat: 페이지 레이아웃 설계 - 사전등록폼
  app/(plain)/account/login/page.tsx
  app/(plain)/account/register/page.tsx
  app/(plain)/landing/page.tsx
  app/(plain)/register/interest/page.tsx
  app/(plain)/register/job/page.tsx
  app/(plain)/register/layout.tsx
  app/(plain)/register/page.tsx
  app/page.tsx
  package-lock.json
  package.json
  src/components/common/input.tsx
  src/components/common/radix-toggle-group.tsx
  src/components/common/round-badge.tsx
  src/components/register/interest-form.tsx
  src/components/register/job-form.tsx
  src/components/register/profile-form.tsx
  src/components/register/register-templete.tsx
  src/constants/interest.ts
  src/constants/job-options.ts
  src/schema/user.ts
  src/utils/use-form-submit.ts
Labels: Feature

#40 fix: react select hydration 오류 픽스
  package-lock.json
  package.json
  patches/react-select+5.10.1.patch
Labels: bug

#44 fix: build 오류 해결
  src/components/common/top-nav.tsx
Labels: bug

#34 feat: 페이지 레이아웃 설계 - mypage, notifications, qr-reader
  app/(main-layout)/mypage/info/page.tsx
  app/(main-layout)/mypage/name-card-list/page.tsx
  app/(main-layout)/mypage/page.tsx
  app/(main-layout)/notifications/page.tsx
  app/(plain)/qr-reader/page.tsx
  package-lock.json
  package.json
  src/components/common/accordion-demo/accordion-demo.tsx
  src/components/common/accordion-demo/style.css
  src/components/common/modal-one-btn.tsx
  src/components/common/modal-two-btn.tsx
  src/components/common/multiple-selection.tsx
  src/components/common/profile.tsx
  src/components/mypage/info-optional.tsx
  src/components/mypage/info-required.tsx
  src/components/mypage/input-field.tsx
  src/components/mypage/mock-user-data.ts
  src/components/mypage/modify-card.tsx
  src/components/mypage/name-card-preview.tsx
  src/utils/download.ts
Labels: Feature

#48 feat: register 기반으로 qr 코드 생성
  app/(plain)/register/interest/page.tsx
  app/(plain)/register/job/page.tsx
  app/(plain)/register/page.tsx
  app/page.tsx
  package-lock.json
  package.json
  src/components/common/input.tsx
  src/components/register/interest-form.tsx
  src/components/register/job-form.tsx
  src/components/register/profile-form.tsx
  src/components/register/register-templete.tsx
  src/constants/job-options.ts
  src/constants/purpose.ts
  src/schema/user.ts
  src/stores/use-form-store.ts
  src/types/.gitignore
  src/types/form.ts
  src/utils/use-form-submit.ts
Labels: Feature

#49 refactor: react-hook-form 변경
  src/components/chat/message-input.tsx
Labels: Improvement

#54 feat: PWA 구축
  app/layout.tsx
  app/manifest.json
  next.config.ts
  package-lock.json
  package.json
  public/.gitignore
  public/images/icons/icon-128.png
  public/images/icons/icon-512.png
  public/sw.js
  public/workbox-f1770938.js
Labels: Feature

#65 fix: build 오류 해결
  app/(main-layout)/notifications/page.tsx
  public/sw.js
  public/workbox-f1770938.js
  src/components/common/radix-tabs.tsx
  src/components/notifications/group-notifications.tsx
  src/components/notifications/one-to-one-notifications.tsx
  src/hooks/use-notifications.ts
Labels: bug

#68 feat: 디자인 시스템 추가 및 모달 리팩토링
  .gitignore
  app/(plain)/account/find-id-pw/page.tsx
  app/(plain)/account/login/page.tsx
  app/layout.tsx
  app/page.tsx
  app/test/page.tsx
  public/sw.js
  src/components/common/button.tsx
  src/components/common/input.tsx
  src/components/common/modal-one-btn.tsx
  src/components/common/modal-two-btn.tsx
  src/components/common/modal.tsx
  src/components/common/profile.tsx
  src/components/common/radix-toggle-group.tsx
  src/components/notification-button.tsx
  src/components/push-notification.tsx
  src/components/register/profile-form.tsx
  src/components/register/register-templete.tsx
  tailwind.config.ts
Labels: Feature

#71 feat: 채팅 UI 구현 및 이미지 추가
  app/(top-layout)/chat/page.tsx
  public/assets/svgs/ExitIcon.svg
  public/assets/svgs/Scanner.svg
  public/assets/svgs/Subtract.svg
  public/images/icons/chat/Profile.png
  public/images/icons/top-navigation/Icons.png
  src/components/chat/chat-bubble.tsx
  src/components/chat/chat-window.tsx
  src/components/chat/message-input.tsx
  src/components/common/default-profile.tsx
  src/components/common/input.tsx
  src/components/common/top-nav.tsx
Labels: Feature

#79 feat : 1:1 채팅 페이지 UI
  app/(top-layout)/chat/page.tsx
  app/(top-layout)/layout.tsx
  app/test-api/page.tsx
  public/assets/svgs/Subtract-on.svg
  public/sw.js
  src/components/chat/chat-bubble.tsx
  src/components/chat/chat-notifier.tsx
  src/components/chat/chat-window.tsx
  src/components/chat/message-input.tsx
  src/components/chat/table-application-card.tsx
  src/components/common/button.tsx
  src/components/common/input.tsx
  src/components/common/modal.tsx
  src/components/common/top-nav.tsx
  src/utils/api.ts
  src/utils/websoket.ts
Labels: Feature

#81 feat : 채팅X (예약) UI 구현
  .gitignore
  app/test-api/page.tsx
  public/assets/svgs/back-arrow.svg
  public/assets/svgs/checkbox-checked.svg
  public/assets/svgs/checkbox-unchecked.svg
  public/assets/svgs/exit-icon.svg
  public/sw.js
  src/components/chat/chat-notifier.tsx
  src/components/chat/chat-window.tsx
  src/components/chat/checkbox-item-modal.tsx
  src/components/chat/message-input.tsx
  src/components/chat/system-message.tsx
  src/components/chat/table-application-card.tsx
  src/components/common/modal.tsx
  src/components/common/top-nav.tsx
  src/components/notifications/notify-card.tsx
  src/utils/api.ts
  src/utils/websoket.ts
Labels: Feature

#88 fix: 빌드 에러 수정
  public/sw.js
  src/components/chat/chat-window.tsx
  src/components/notifications/notify-card.tsx
Labels: bug

#94 테이블 페이지 UI 구현
  app/(plain)/table/page.tsx
  public/assets/svgs/check-circle.svg
  src/components/common/modal.tsx
  src/components/table/networking-actions.tsx
  src/components/table/table-remaining-time.tsx
  src/components/table/table-usage-rules.tsx
Labels: Feature

#99 feat: 회원 api 연결 및 회원등록 폼 수정
  app/(plain)/[entry]/register/job/page.tsx
  app/(plain)/[entry]/register/layout.tsx
  app/(plain)/[entry]/register/network/page.tsx
  app/(plain)/[entry]/register/page.tsx
  app/(plain)/account/find-id-pw/page.tsx
  app/(plain)/account/login/page.tsx
  app/(plain)/pre/page.tsx
  app/(plain)/welcome/page.tsx
  app/layout.tsx
  app/middleware.ts
  public/assets/svgs/eye-off.svg
  public/assets/svgs/eye.svg
  src/components/common/input.tsx
  src/components/login-form.tsx
  src/components/register/agree-button.tsx
  src/components/register/job-form.tsx
  src/components/register/network-form.tsx
  src/components/register/profile-form.tsx
  src/components/register/register-templete.tsx
  src/schema/user.ts
  src/stores/use-form-store.ts
  src/stores/use-network-store.ts
  src/types/form.ts
  src/utils/api/api.ts
  src/utils/api/user.ts
  src/utils/format-form-data.ts
  src/utils/use-form-submit.ts
Labels: Feature

#103 feat: 마이페이지 리팩토링 및 api 연결
  app/(main-layout)/home/page.tsx
  app/(main-layout)/mypage/name-card-list/page.tsx
  app/(main-layout)/mypage/page.tsx
  app/(main-layout)/notifications/page.tsx
  app/(plain)/[entry]/register/profile/page.tsx
  app/(plain)/pre/page.tsx
  app/(top-layout)/layout.tsx
  app/(top-layout)/mypage/edit-profile/page.tsx
  app/(top-layout)/mypage/name-card-list/page.tsx
  app/page.tsx
  middleware.ts
  src/components/common/select-field.tsx
  src/components/common/top-nav.tsx
  src/components/mypage/card-dialog.tsx
  src/components/mypage/card-item.tsx
  src/components/mypage/detail-card.tsx
  src/components/mypage/info-optional.tsx
  src/components/mypage/info-required.tsx
  src/components/mypage/input-field.tsx
  src/components/mypage/modify-card.tsx
  src/components/mypage/name-card-preview.tsx
  src/components/register/profile-form.tsx
  src/hooks/use-notifications.ts
  src/stores/use-card-store.ts
  src/stores/use-form-store.ts
  src/stores/use-network-store.ts
  src/styles/globals.css
  src/styles/react-select.tsx
  src/types/form.ts
  src/utils/api/user.ts
  src/utils/format-form-data.ts
  src/utils/get-top-nav-type.ts
  src/utils/use-form-submit.ts
Labels: Feature

#105 feat: 푸시 알림 테스트
  app/api/send-push/route.ts
  app/page.tsx
  app/test/page.tsx
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/components/notification-button.tsx
  src/stores/use-network-store.ts
  src/utils/firebase/firebase.ts
  src/utils/firebase/get-fcm-token.ts
  src/utils/firebase/request-permission.ts
Labels: Feature

#109 fix: vercel proxy 에러
  .gitignore
  middleware.ts
  vercel.json
Labels: bug

#121 feat: quick-network 페이지 구현
  app/(plain)/welcome/page.tsx
  app/(top-layout)/chat/page.tsx
  app/(top-layout)/mypage/edit-profile/page.tsx
  app/(top-layout)/quick-network/page.tsx
  next.config.ts
  package-lock.json
  package.json
  public/assets/svgs/checkbox-circle-false.svg
  public/assets/svgs/checkbox-circle-true.svg
  public/assets/svgs/logo.svg
  src/components/chat/chat-bubble.tsx
  src/components/chat/chat-window.tsx
  src/components/common/quick-network/icon-rolling.tsx
  src/components/common/quick-network/text.rolling.tsx
  src/components/common/quick-network/welcome-icon/bird.tsx
  src/components/common/quick-network/welcome-icon/cat.tsx
  src/components/common/quick-network/welcome-icon/dog.tsx
  src/components/common/quick-network/welcome-icon/jelly-fish.tsx
  src/components/common/quick-network/welcome-icon/koala.tsx
  src/components/common/quick-network/welcome-icon/monkey.tsx
  src/components/common/quick-network/welcome-icon/otter.tsx
  src/components/common/quick-network/welcome-icon/quokka.tsx
  src/components/common/quick-network/welcome-icon/rabbit.tsx
  src/components/common/quick-network/welcome-icon/snail.tsx
  src/components/common/quick-network/welcome-icon/snowman.tsx
  src/components/common/quick-network/welcome-icon/whale.tsx
  src/components/common/top-nav.tsx
  src/utils/get-top-nav-type.ts
  tailwind.config.ts
Labels: Feature

#122 refactor: svgr 설치 및 변경된 아이콘 적용
  app/(main-layout)/mypage/page.tsx
  app/(top-layout)/quick-network/page.tsx
  next.config.ts
  public/assets/svgs/Scanner.svg
  public/assets/svgs/qr-code.svg
  src/assets/svgs/Plus.svg
  src/assets/svgs/Subtract-on.svg
  src/assets/svgs/Subtract.svg
  src/assets/svgs/arrow.svg
  src/assets/svgs/back-arrow.svg
  src/assets/svgs/bookmark.svg
  src/assets/svgs/card.svg
  src/assets/svgs/check-circle.svg
  src/assets/svgs/checkbox-checked.svg
  src/assets/svgs/checkbox-circle-false.svg
  src/assets/svgs/checkbox-circle-true.svg
  src/assets/svgs/checkbox-unchecked.svg
  src/assets/svgs/exit-icon.svg
  src/assets/svgs/eye-off.svg
  src/assets/svgs/eye.svg
  src/assets/svgs/filter.svg
  src/assets/svgs/home_filled.svg
  src/assets/svgs/logo.svg
  src/assets/svgs/notification_filled.svg
  src/assets/svgs/user_filled.svg
  src/components/card/match-card.tsx
  src/components/card/match-group.tsx
  src/components/card/match-one-to-one.tsx
  src/components/chat/checkbox-item-modal.tsx
  src/components/chat/message-input.tsx
  src/components/common/accordion/accordion.tsx
  src/components/common/bottom-nav.tsx
  src/components/common/card-basic.tsx
  src/components/common/input.tsx
  src/components/common/top-nav.tsx
  src/components/match/filter.tsx
  src/components/table/table-usage-rules.tsx
Labels: Refactor

#139 fix: 빌드오류 수정
  app/(main-layout)/home/page.tsx
  app/(top-layout)/create-group/page.tsx
  package-lock.json
  package.json
  src/components/card/match-card.tsx
  src/components/card/match-group.tsx
  src/components/card/match-one-to-one.tsx
  src/components/common/default-profile.tsx
  src/components/match/career-slider.tsx
  src/components/match/group.tsx
  src/components/mypage/card-item.tsx
  src/stores/use-group-match-store.ts
  src/styles/globals.css
  src/types/group.types.ts
  src/types/user.types.ts
  src/utils/get-top-nav-type.ts
Labels: bug

#135 feat: 그룹 매칭 페이지 구현
  app/(main-layout)/home/page.tsx
  src/components/login-form.tsx
Labels: Feature

#143 feat : quick-network 페이지 수정
  app/(plain)/welcome/page.tsx
  app/(top-layout)/ios-notification/page.tsx
  app/(top-layout)/quick-network/page.tsx
  src/assets/svgs/share.svg
  src/components/mypage/card-item.tsx
  src/utils/get-top-nav-type.ts
Labels: Feature

#147 feat: 네트워크 토글에서 알림 허가 받기
  app/(main-layout)/home/page.tsx
  app/(top-layout)/chat/page.tsx
  app/test/page.tsx
  public/firebase-messaging-sw.js
  src/components/chat/chat-bubble.tsx
  src/components/mypage/card-item.tsx
  src/stores/use-network-store.ts
  src/utils/firebase/firebase.ts
Labels: Feature

#149 feat: quick-network 수정사항
  app/(top-layout)/create-group/page.tsx
  app/(top-layout)/ios-notification/page.tsx
  app/test-api/page.tsx
  package-lock.json
  package.json
  src/components/common/quick-network/icon-rolling.tsx
  src/components/common/quick-network/text.rolling.tsx
  src/components/match/group.tsx
  src/components/mypage/detail-card.tsx
  src/components/register/toggle-field.tsx
  src/utils/api/user.ts
Labels: Feature

#154 feat: 알림요청 UI
  app/(main-layout)/home/page.tsx
  app/(top-layout)/chat/page.tsx
  app/(top-layout)/create-group/page.tsx
  src/components/common/modal.tsx
  src/components/match/group.tsx
  src/components/register/toggle-field.tsx
Labels: Feature

#160 feat: 그룹 카드 ui 및 채팅알림 ui 구현
  app/(main-layout)/home/page.tsx
  app/(top-layout)/create-group/page.tsx
  src/assets/svgs/qr-code-ver1.svg
  src/components/common/top-nav.tsx
  src/components/match/career-slider.tsx
  src/components/match/group.tsx
  src/components/register/toggle-field.tsx
Labels: Feature

#161 fix: build error
  app/(main-layout)/home/page.tsx
  app/(top-layout)/chat/page.tsx
  app/(top-layout)/create-group/page.tsx
  src/components/chat/chat-bubble.tsx
  src/components/common/qr-scanner.tsx
  src/components/common/quick-network/icon-rolling.tsx
  src/components/mypage/card-item.tsx
Labels: bug

#164 feat: protocol에 따라 ws or wss 설정되도록 로직 추가
  app/(main-layout)/home/page.tsx
  app/(main-layout)/user-info/[userId]/page.tsx
  app/(top-layout)/chat/page.tsx
  src/components/match/modal-for-match.tsx
  src/utils/websoket.ts
Labels: Feature

#166 chore: config 수정
  next.config.ts
  vercel.json
Labels: bug

#185 feat: 미들웨어 설정
  app/(plain)/login/page.tsx
  middleware.ts
  next.config.ts
Labels: Feature
